# Generated by Django 4.2.5 on 2023-09-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.product'),
            preserve_default=False,
        ),
    ]
