# Generated by Django 4.2.5 on 2023-09-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0008_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='view', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
