# Generated by Django 4.2.5 on 2023-09-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_view_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='viewed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
