# Generated by Django 4.2.5 on 2023-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_view_viewed_alter_lesson_duration_alter_lesson_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
