# Generated by Django 4.2.5 on 2023-09-20 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0012_remove_product_lesson_lesson_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='student',
            field=models.ManyToManyField(related_name='availableProducts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
