# Generated by Django 4.2.5 on 2023-09-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_product_student_delete_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='lessons.lesson'),
        ),
    ]
