# Generated by Django 4.2.5 on 2023-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_view_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='lastViewed',
            field=models.DateTimeField(null=True),
        ),
    ]
