# Generated by Django 4.2.5 on 2023-09-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0016_view_lastviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='view',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='view',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
